projeto_agenda/contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('contact/create', views.create, name='create'),
    path('contact/<int:contact_id>/read', views.contact, name='contact'),
    path('contact/<int:contact_id>/update', views.contact, name='contact'),
    path('contact/<int:contact_id>/delete', views.contact, name='contact'),

    # path('<int:contact_id>/', views.contact, name='contact'),

    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

projeto_agenda/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto_agenda/contact/models.py
from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return f'{self.name}'
 
class Contact(models.Model):

    primeiro_nome = models.CharField(max_length=20)
    ultimo_nome = models.CharField(max_length=20, blank=True)
    celular = models.CharField(max_length=20) 
    email = models.EmailField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self) -> str:
        return f'{self.primeiro_nome} {self.ultimo_nome}'

projeto_agenda/contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        'contact/index.html'
    )

projeto_agenda/contact/views/contact_forms.py
from django.shortcuts import get_list_or_404, redirect, render
from contact.models import Contact

def create(request):
    print(request.POST.get('first_name'))

    context = {

    }

    return render(
        request,
        'contact/create.html',
        context
    )

projeto_agenda/contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contact
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context ={
        'page_obj': page_obj,
        'site_title': 'Contatos -',
    }

    return render(
        request,
        'contact/index.html',
        context
    )  

# Create your views here.
def contact(request, contact_id):
    #single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(Contact, pk=contact_id,show=True)

    contact_name = f'{single_contact.primeiro_nome} {single_contact.ultimo_nome}'

    context ={
        'contact': single_contact,
        'site_title': contact_name,
    }

    return render(
        request,
        'contact/contact.html',
        context
    )  

# Create your views here.
def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')
    
    print(search_value)

    contacts = Contact.objects\
            .filter(show=True)\
            .filter(
                Q(primeiro_nome__contains=search_value)
                |
                Q(ultimo_nome__contains=search_value)
            )\
            .order_by('-id')\
            
    print(contacts.query)

    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)


    context ={
        'page_obj': page_obj,
        'site_title': 'Search -',
    }

    return render(
        request,
        'contact/index.html',
        context
    )  

projeto_agenda/contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{contact.primeiro_nome}} {{contact.ultimo_nome}}
    </h1>
    <p><b>ID:</b>{{contact.id}}</p>
    <p><b>CELULAR:</b>{{contact.celular}}</p>
    <p><b>EMAIL:</b>{{contact.email}}</p>
    <p><b>DATA DE CRIAÇÃO:</b>{{contact.created_date}}</p>
    <p><b>DESCRIÇÃO:</b>{{contact.description}}</p>
    <p><b>SHOW:</b>{{contact.show}}</p>
    <p><b>FOTO:</b>{{contact.picture}}</p>
    <p><b>CATEGORIA:</b>{{contact.category.name}}</p>
    <p><b>OWNER:</b>{{contact.owner}}</p>

</div>
{% endblock content %}

projeto_agenda/contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}

    <div class="form-wrapper">
        <h2>Contact</h2>
        <form action="{% url "contact:create" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-content">
                <div class="form-group">
                    <label for="id_first_name">LABEL</label>
                    <input type="text" name="first_name" maxlength="255" id="id_first_name">
                </div>
            </div>
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>


{% endblock content %}

projeto_agenda/contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
        <caption class="table-caption">
            Contacts
        </caption>
        
        <thead>
            <tr class="tablerow table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">Primeiro Nome</th>
                <th class="table-header">Ultimo Nome</th>
                <th class="table-header">Celular</th>
                <th class="table-header">Email</th>
            </tr>
        </thead>

        <tbody>
            {% for contact in page_obj%}
                <tr class="table-row">
                    <td class="tablecel">
                        <a 
                            href="{% url "contact:contact" contact.id %}" 
                            class="table-link">

                            {{contact.id}}
                        </a>
                    </td>
                    <td class="tablecel">
                        {{contact.primeiro_nome}}
                    </td>
                    <td class="tablecel">
                        {{contact.ultimo_nome}}
                    </td>
                    <td class="tablecel">
                        {{contact.celular}}
                    </td>
                    <td class="tablecel">
                        {{contact.email}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>

        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Usuario não encontrado
    </h1>
</div>
{% endif %}
{% endblock content %}