ola_django/home/urls.py
from django.urls import path

from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.home_view, name='url_da_home'),
    path('<int:post_id>/', views.post_view, name='post'),
    path('teste/', views.teste_view, name='url_de_teste')
]

ola_django/home/views.py
from django.shortcuts import render
from home.data import posts
from django.http import HttpRequest, Http404

def home_view(request):

    context = {
        'text' : 'Olá Home',
        'title' : 'HOME',
        'posts' : posts
    }

    return render(request, 'pasta_home/home.html', context)

def post_view(request:HttpRequest, post_id:int):
    found_post = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post não existe')

    context = {
        'text' : 'Olá Post',
        'title' : found_post['title'],
        'posts' : [found_post]  # Passando o post diretamente, não como uma lista
    }

    return render(request, 'pasta_home/post.html', context)

def teste_view(request):

    context = {
        'text' : 'Olá Teste',
        'title' : 'TESTE',
        'posts' : posts
    }

    return render(request, 'pasta_home/teste.html',context)

ola_django/home/templates/pasta_home/home.html
{% extends "global/index.html" %}

{% block titulo %}{{title}}{% endblock titulo %}

{% block Mensagem %}
<h1>VOCE ESTA NA PAGINA INICIAL, BEM VINDO BICHÃOO</h1>
{% endblock Mensagem %}

{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

ola_django/home/templates/pasta_home/post.html
{% extends "global/index.html" %}

{% block titulo %}{{ title }}{% endblock titulo %}

{% block Mensagem %}
<h1>VOCÊ ESTÁ NA PÁGINA INICIAL, BEM-VINDO!</h1>
{% endblock Mensagem %}

{% block posts %}
    {% for post in posts %}
    <article class="post single-post">
        <header>
            <h1 class="post__title">
                <a href="{% url "Home:post" post.id %}">
                    {{ post.title }}
                </a>
            </h1>
        </header>
        <div class="post__body">{{ post.body }}</div>
    </article>
    {% endfor %}
{% endblock posts %}

ola_django/home/templates/pasta_home/teste.html
{% extends "global/index.html" %}
{% block titulo %}{{title}}{% endblock titulo %}

{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}